# CrystalSpace - plugin.yml
# All developers/contributors are here!

name: CrystalSpace
main: com.crystalcraftmc.crystalspace.Space
version: 3.1.0
api-version: '1.21'
authors: [kitskub, iffa, SwearWord, HACKhalo2, Canis85, BR, jflory7, Jacc734, Jwood9198, atkoliver ]
website: https://github.com/atkoliver/CrystalSpace
# jenkins-url:

# Load on startup for bukkit.yml, and all that support
load: startup
softdepend: [Register]

# Commands
commands:
  space:
    description: Go to space, back to earth etc.
    usage: |
          /<command> <enter> [spaceworld] - Go to a space world
          /<command> <back> - Go back where you were
          /<command> <list> - Lists all spaceworlds (loaded with config.yml)
          /<command> <help> - Shows help (usage)
          /<command> <about> - About CrystalSpace

# Permission nodes
permissions:
  
  # All command permissions group
  CrystalSpace.commands.*:
    description: Access to all CrystalSpace commands.
    children:
      CrystalSpace.teleport.*: true
  
  # Ignores
  CrystalSpace.ignore.*:
    description: Access to all ignore permissions (currently, only "ignore suit check").
    children:
      CrystalSpace.ignoresuitchecks: true
  
  # Teleport
  CrystalSpace.teleport.*:
    description: Access to all teleportation commands.
    children:
      CrystalSpace.teleport.enter: true
      CrystalSpace.teleport.exit: true
      CrystalSpace.teleport.list: true
  
  # Single permissions
  CrystalSpace.teleport.enter:
    description: Allows teleporting to space.
    default: op
  CrystalSpace.teleport.exit:
    description: Allows teleporting out of space.
    default: op
  CrystalSpace.teleport.list:
    description: Allows requesting list of spaceworlds.
    default: op