# DuzySpace - plugin.yml
# All developers/contributors are here!

name: DuzySpace
main: com.atkoliver.duzyspace.Space
version: 3.1.0
api-version: '1.21'
authors: [kitskub, iffa, SwearWord, HACKhalo2, Canis85, BR, jflory7, Jacc734, Jwood9198, atkoliver ]
website: https://github.com/atkoliver/DuzySpace
# jenkins-url:

# Load on startup for bukkit.yml, and all that support
load: startup
softdepend: [Register]

# Commands
commands:
  space:
    description: Go to space, back to earth etc.
    usage: |
          /<command> <enter> [spaceworld] - Go to a space world
          /<command> <back> - Go back where you were
          /<command> <list> - Lists all spaceworlds (loaded with config.yml)
          /<command> <help> - Shows help (usage)
          /<command> <about> - About DuzySpace

# Permission nodes
permissions:
  
  # All command permissions group
  DuzySpace.commands.*:
    description: Access to all DuzySpace commands.
    children:
      DuzySpace.teleport.*: true
  
  # Ignores
  DuzySpace.ignore.*:
    description: Access to all ignore permissions (currently, only "ignore suit check").
    children:
      DuzySpace.ignoresuitchecks: true
  
  # Teleport
  DuzySpace.teleport.*:
    description: Access to all teleportation commands.
    children:
      DuzySpace.teleport.enter: true
      DuzySpace.teleport.exit: true
      DuzySpace.teleport.list: true
  
  # Single permissions
  DuzySpace.teleport.enter:
    description: Allows teleporting to space.
    default: op
  DuzySpace.teleport.exit:
    description: Allows teleporting out of space.
    default: op
  DuzySpace.teleport.list:
    description: Allows requesting list of spaceworlds.
    default: op